version:
  name: velociraptor
  version: 0.6.9
  commit: be0af2d
  build_time: "2023-05-24T23:33:19Z"
  install_time: 1724005284
  ci_build_url: https://github.com/Velocidex/velociraptor/actions/runs/5074403308
  compiler: go1.20.4
Client:
  server_urls:
  - https://10.5.20.3:8000/
  ca_certificate: |
    -----BEGIN CERTIFICATE-----
    MIIDSzCCAjOgAwIBAgIQS3J7xiQkmRGukC4TNDuG1zANBgkqhkiG9w0BAQsFADAa
    MRgwFgYDVQQKEw9WZWxvY2lyYXB0b3IgQ0EwHhcNMjQwODE4MTgyMTUxWhcNMzQw
    ODE2MTgyMTUxWjAaMRgwFgYDVQQKEw9WZWxvY2lyYXB0b3IgQ0EwggEiMA0GCSqG
    SIb3DQEBAQUAA4IBDwAwggEKAoIBAQDb1mKUCEQDfueCvsfmxmbPxo0vEQigvjoI
    XG+F1H1AqlS3/NN/WHZGWLRhI5IT1RxZWRACFWTS8O1yKojMyVzwfPxUxuVUEK8D
    4U4CvtDR6GMv96CBUk6gtqcbxiXQ7PHdn0fhvyRk8Y4Ima6pg4EUCsonFm6voa6R
    Zi6oBTO9l3e7wgxdAVJ6jOxUOdDLLWqhCz7smMcLVssw4QfTe8xYp2l/BvzuZU+l
    xL5iWmiTXEg9htChD2k0Cc3UNzHfxhTqL902e577i92blOjbxKBFVnryVdBCxQtV
    6IaY8yurQFLtPg+A6sSUVi8VzlFxZ3CxbgoE+VPcDQi3GchHujDlAgMBAAGjgYww
    gYkwDgYDVR0PAQH/BAQDAgKkMB0GA1UdJQQWMBQGCCsGAQUFBwMBBggrBgEFBQcD
    AjAPBgNVHRMBAf8EBTADAQH/MB0GA1UdDgQWBBTliSoFsvzQ6BpyekEL+YQo5Bdi
    4DAoBgNVHREEITAfgh1WZWxvY2lyYXB0b3JfY2EudmVsb2NpZGV4LmNvbTANBgkq
    hkiG9w0BAQsFAAOCAQEAWSMwbif3CngBpaezKpOnVEmY+cnfsz6lTuinJ51l4Ns+
    NJETtJkm+XlKtVmahyK14mKvSFq1K+0MaVEIpVT+JAccdn0uYa7xxMkrHZotkajd
    fLtXdH0/n1IHYqe70l7s5SgwvPoDb+TIiU3iyocb/2VQJYsGKQX7FUZ8t/kHp2kC
    oJ7t5kwFx4FhtpMOD/CaHisztnGGgo+HuGBb8WI/TMJinzUvLGfw5fuKUEi87ClA
    z4YyLa3hD1ne/bNRw7IJ21+wRRU6Gqpm8EpdCKvFjovFay3HVLcwkPEAg5ZXVsFE
    aea111sB91mlsVh5Bt5GcSgrzXaKRgaMv0ZBW+iAtQ==
    -----END CERTIFICATE-----
  nonce: 18nzzyFisQ8=
  writeback_darwin: /etc/velociraptor.writeback.yaml
  writeback_linux: /etc/velociraptor.writeback.yaml
  writeback_windows: $ProgramFiles\Velociraptor\velociraptor.writeback.yaml
  tempdir_windows: $ProgramFiles\Velociraptor\Tools
  max_poll: 60
  nanny_max_connection_delay: 600
  windows_installer:
    service_name: Velociraptor
    install_path: $ProgramFiles\Velociraptor\Velociraptor.exe
    service_description: Velociraptor service
  darwin_installer:
    service_name: com.velocidex.velociraptor
    install_path: /usr/local/sbin/velociraptor
  version:
    name: velociraptor
    version: 0.6.9
    commit: be0af2d
    build_time: "2023-05-24T23:33:19Z"
    install_time: 1724005284
    ci_build_url: https://github.com/Velocidex/velociraptor/actions/runs/5074403308
    compiler: go1.20.4
  use_self_signed_ssl: true
  pinned_server_name: VelociraptorServer
  max_upload_size: 5242880
  local_buffer:
    memory_size: 52428800
    disk_size: 1073741824
    filename_linux: /var/tmp/Velociraptor_Buffer.bin
    filename_windows: $TEMP/Velociraptor_Buffer.bin
    filename_darwin: /var/tmp/Velociraptor_Buffer.bin
