---

- name: Converge
  hosts: all
  environment:
    http_proxy: "{{ lookup('env', 'http_proxy') }}"
    https_proxy: "{{ lookup('env', 'https_proxy') }}"
    no_proxy: "{{ lookup('env', 'no_proxy') }}"
  remote_user: root
  vars:
    velociraptor_client: true
    velociraptor_server: true
    velociraptor_admin_password: password
    velociraptor_frontend_base_path: 'frontend'
    # velociraptor_fqdn: velociraptor.example.com
    velociraptor_fqdn: "{{ ansible_fqdn }}"
    hardenwebserver_disable_http: true
    hardenwebserver_cert: mkcert
    hardenwebserver_https_template: ../../templates/nginx.conf.j2
    # hardenwebserver_header_csp: "default-src 'self'; script-src 'self' 'unsafe-inline' 'report-sample'; connect-src 'self'; img-src 'self'; style-src 'self' 'unsafe-inline' 'unsafe-eval'; font-src 'self' data:;base-uri 'none'; frame-ancestors 'none'; form-action 'self'; upgrade-insecure-requests; report-uri /csp/report.php;"
    hardenwebserver_header_csp: "upgrade-insecure-requests; report-uri /csp/report.php;"
    # hardenwebserver_ssl_cert: "/etc/letsencrypt/live/{{ velociraptor_fqdn }}/fullchain.pem"
    # hardenwebserver_ssl_key: "/etc/letsencrypt/live/{{ velociraptor_fqdn }}/privkey.pem"
    hardenwebserver_systemd_dir_acl:
      - { p: /etc/letsencrypt/archive, perm: rx, m: '0711' }
      - { p: /etc/letsencrypt/live, perm: rx, m: '0711' }
      - { p: "/etc/ssl/private", perm: rx, m: '0710' }
      - { p: "/var/log/nginx", perm: rwx, m: '0755' }
    hardenwebserver_systemd_files_acl:
      # - { p: "/etc/letsencrypt/live/{{ velociraptor_fqdn }}/privkey.pem", perm: r }
      - { p: "/etc/ssl/private/{{ velociraptor_fqdn }}.key", perm: r }
      - { p: "/etc/ssl/private/dhparam4.pem", perm: r }
  pre_tasks:
    - name: Ubuntu | Install python3
      ansible.builtin.raw: test -e /usr/bin/python3 || (apt -y update && apt install -y python3-minimal)
      register: python3
      changed_when: "'installed' in python3.stdout"
      when: >
        (ansible_distribution == "Ubuntu" and ansible_distribution_major_version|int >= 16) or
        (ansible_distribution == "Debian" and ansible_distribution_major_version|int >= 10)
    - name: RedHat | Install python3
      ansible.builtin.raw: test -e /usr/bin/python3 || (yum install -y python3)
      register: python3
      changed_when: "'installed' in python3.stdout"
      when: (ansible_os_family == "RedHat" and ansible_distribution_major_version | int >= 7)
    - name: Python3
      when: >
        (ansible_distribution == "Ubuntu" and ansible_distribution_major_version|int >= 16) or
        (ansible_distribution == "Debian" and ansible_distribution_major_version|int >= 10) or
        (ansible_os_family == "RedHat" and ansible_distribution_major_version|int >= 7)
      block:
        - name: Gather Facts
          ansible.builtin.setup:
        - name: Ubuntu Bionic+, Redhat 8+ | Enforce python3 for ansible
          ansible.builtin.set_fact:
            ansible_python_interpreter: /usr/bin/python3
    - name: Set hostname
      ansible.builtin.hostname:
        name: "{{ velociraptor_fqdn }}"
      when: velociraptor_fqdn | length <= 64
  roles:
    - prymalinstynct.velociraptor
    - juju4.harden_nginx
