- name: DownloadConfig
  ansible.builtin.get_url:
    dest: "/etc/velociraptor/client.config.yaml"
    url: https://raw.githubusercontent.com/BarrySploit/Ludus-Ansible/main/client.config.yaml
    force: true
- name: RestartSvc
  ansible.builtin.service:
    name: velociraptor
    state: restarted